package database

import (
	"database/sql"
	"fmt"

	"github.com/thinkbig1979/capstan/backend/internal/models"
)

// --- Docker Cleanup Runs ---

// CreateDockerCleanupRun records one cleanup execution. The id is generated by
// the caller (uuid.New().String() at the service layer), the same split
// CreateBackupRun uses -- internal/database generates no ids of its own.
func (d *DB) CreateDockerCleanupRun(r *models.DockerCleanupRun) error {
	query := `INSERT INTO docker_cleanup_runs (id, trigger, status, started_at, finished_at, images_deleted, bytes_reclaimed, cache_bytes_reclaimed, min_age_hours, error_message)
	          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// agent-os-fn7x.8: started_at and finished_at are ORDERed and compared as
	// TEXT -- GetDockerCleanupRuns below sorts on started_at -- so a row
	// written in a local-offset or sub-second spelling does not sort by
	// instant against a UTC one. canonicalTimestamp is the same write-side
	// chokepoint update_history uses, and migration 15 exists because that
	// table learned this the expensive way: a mixed table keeps mis-sorting
	// until retention prunes the old rows, which can take months.
	//
	// The option NOT taken was to bind verbatim and name the spelling in each
	// writer's brief, which is what backup_runs does -- its one writer spells
	// it correctly in BackupRunnerRegistry.LaunchBackup and nothing enforces
	// that. It keeps the two run tables consistent with each other, at the
	// cost of relying on every caller added later getting it right. That
	// reliance is exactly what failed for update_history, so this table gets
	// the chokepoint instead: a caller cannot forget it. backup_runs is left
	// as it was rather than changed from here; it is tracked as agent-os-zsgy.
	//
	// Normalised into locals, never back into *r -- the caller owns that
	// struct and may reuse it after the write.
	startedAt := canonicalTimestamp(r.StartedAt)
	var finishedAt interface{}
	if r.FinishedAt != nil {
		finishedAt = canonicalTimestamp(*r.FinishedAt)
	}

	_, err := d.db.Exec(query, r.ID, r.Trigger, r.Status, startedAt, finishedAt,
		r.ImagesDeleted, r.BytesReclaimed, r.CacheBytesReclaimed, r.MinAgeHours, r.ErrorMessage)
	return err
}

// GetDockerCleanupRuns returns the most recent cleanup runs, newest first.
func (d *DB) GetDockerCleanupRuns(limit int) ([]models.DockerCleanupRun, error) {
	query := `SELECT id, trigger, status, started_at, finished_at, images_deleted, bytes_reclaimed, cache_bytes_reclaimed, min_age_hours, error_message
	          FROM docker_cleanup_runs ORDER BY started_at DESC LIMIT ?`
	rows, err := d.db.Query(query, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var runs []models.DockerCleanupRun
	for rows.Next() {
		var r models.DockerCleanupRun
		// error_message is nullable and only ever written non-NULL by
		// CreateDockerCleanupRun; NullString keeps a row inserted by hand (or
		// by a future writer that omits the column) from failing the scan.
		var errorMessage sql.NullString
		err := rows.Scan(&r.ID, &r.Trigger, &r.Status, &r.StartedAt, &r.FinishedAt,
			&r.ImagesDeleted, &r.BytesReclaimed, &r.CacheBytesReclaimed, &r.MinAgeHours, &errorMessage)
		if err != nil {
			return nil, err
		}
		r.ErrorMessage = errorMessage.String
		runs = append(runs, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("reading docker cleanup runs: %w", err)
	}
	return runs, nil
}
