// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/services/wire_types.go. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: wire_types.go

/**
 * DiskUsageBreakdown is the per-category Docker disk usage served inside
 * GET /dashboard/stats's diskUsage field.
 */
export interface DiskUsageBreakdown {
  images: number /* int64 */;
  containers: number /* int64 */;
  volumes: number /* int64 */;
  buildCache: number /* int64 */;
  total: number /* int64 */;
}
/**
 * DockerCleanupCandidate is one image a run would remove. Repository is empty
 * for the fully-untagged form; see danglingRepository.
 */
export interface DockerCleanupCandidate {
  id: string;
  repository?: string;
  size: number /* int64 */;
  created: number /* int64 */;
}
/**
 * DockerCleanupPreview is what a run WOULD remove. Producing it must not remove
 * anything.
 */
export interface DockerCleanupPreview {
  candidates: DockerCleanupCandidate[];
  reclaimableBytes: number /* int64 */;
  minAgeHours: number /* int */;
}
/**
 * Status represents the lifecycle state of an update job.
 */
export const StatusQueued = "queued";
export const StatusPulling = "pulling";
export const StatusRecreating = "recreating";
export const StatusSuccess = "success";
export const StatusError = "error";
export type Status = typeof StatusQueued | typeof StatusPulling | typeof StatusRecreating | typeof StatusSuccess | typeof StatusError;
/**
 * Stream is one of the three allowed stream values for a LogLine.
 */
export const StreamStdout = "stdout";
export const StreamStderr = "stderr";
export const StreamStatus = "status";
export type Stream = typeof StreamStdout | typeof StreamStderr | typeof StreamStatus;
/**
 * JobTargetType is what an update job updates: one container or a whole stack.
 */
export const JobTargetTypeContainer = "container";
export const JobTargetTypeStack = "stack";
export type JobTargetType = typeof JobTargetTypeContainer | typeof JobTargetTypeStack;
