// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/truth. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: outcome.go
/*
Package truth provides the Action Truth Contract primitives: typed outcomes,
consistent HTTP rendering, and helpers that every domain action uses to prove
its effects rather than trusting proxy signals such as exit codes.
*/

/**
 * Outcome is the canonical result class for every mutating action.
 */
/**
 * OutcomeSuccess means the action completed and its effect was verified.
 */
export const OutcomeSuccess = "success";
/**
 * OutcomeNoChange means the resource was already in the desired state;
 * the action was a verified no-op (e.g. image already up to date).
 */
export const OutcomeNoChange = "no_change";
/**
 * OutcomePartial means the action succeeded for a subset of targets;
 * at least one sub-operation failed. HTTP 207.
 */
export const OutcomePartial = "partial";
/**
 * OutcomeFailed means the action failed; the resource is unchanged or
 * left in an indeterminate state.
 */
export const OutcomeFailed = "failed";
export type Outcome = typeof OutcomeSuccess | typeof OutcomeNoChange | typeof OutcomePartial | typeof OutcomeFailed;
/**
 * ActionResult is the return type for every mutating action.
 * Err is intentionally excluded from JSON so the wire format stays clean;
 * callers use Err for internal error propagation.
 */
export interface ActionResult {
  outcome: Outcome;
  reason: string;
  details?: { [key: string]: unknown};
}

//////////
// source: pullstream.go

