// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/handlers/wire_types.go. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: wire_types.go

/**
 * EnvEntry is the wire shape of one line of a stack's env file. It is
 * bidirectional: it is both what GET /:id/env returns (EnvResponse.Entries)
 * and what PUT /:id/env accepts (EnvRequest.Entries); the editor's draft row
 * is derived from it (EnvEntryDraft in frontend/src/types/index.ts, extended
 * by EnvEntryRow in frontend/src/components/stack/env-editor/types.ts). Its TypeScript counterpart is generated from this
 * file into frontend/src/types/generated-handlers.ts (backend/tygo.yaml) and
 * re-exported by frontend/src/types/index.ts; env_wire_contract_test.go pins
 * the tag choices below on the real encoder.
 * Sensitive carries no omitempty on purpose (agent-os-6wrb). TypeScript
 * declares `sensitive: boolean` as REQUIRED, so omitting the key on false
 * made the declared type a lie: every consumer read the absent value as
 * false and was right only because undefined is falsy. It is a
 * security-relevant masking hint, so the wire is matched to the strict
 * declaration rather than the declaration loosened to a lossy wire.
 * Comment keeps omitempty because TypeScript declares it OPTIONAL
 * (`comment?: boolean`); that pair already agrees.
 * Line carries no omitempty because every RESPONSE carries it and it is
 * never 0 there: parseEnvFile increments lineNum before use, so it is 1-based
 * at every construction site on the response path. The generated TypeScript therefore declares
 * `line: number` as required, and that is the response contract. The REQUEST
 * role is stated separately on the frontend, by the hand-written EnvEntryDraft
 * in frontend/src/types/index.ts (the editor's draft row, which has no line
 * until the file is saved and re-parsed); an absent line decodes here as 0
 * and nothing on the request path reads it (agent-os-tuxp).
 */
export interface EnvEntry {
  key: string;
  value: string;
  line: number /* int */;
  sensitive: boolean;
  comment?: boolean;
}
/**
 * EnvResponse is the wire shape of GET /:id/env when the stack HAS an env file.
 * HasEnvFile is always true here and is not omitempty: the no-file answer is a
 * separate 200 payload carrying `{"hasEnvFile": false}` and nothing else
 * (agent-os-bt5y), so the field has to be present on both branches for a client
 * to discriminate on it.
 * Raw is omitempty and Locked is set because the response is redacted for a
 * session that has not re-entered its password: see redactEnvResponse. A caller
 * must therefore treat a missing "raw" as "not authorised to see it", not as
 * "the file is empty" — Locked tells the two apart.
 */
export interface EnvResponse {
  hasEnvFile: boolean;
  filename: string;
  entries: EnvEntry[];
  raw?: string;
  locked?: boolean;
}
/**
 * BuildCacheEntry is our own wire representation of a Docker build-cache
 * record.
 * The endpoint used to serialize build.CacheRecord from the Docker SDK
 * straight to the wire, which made it the only PascalCase payload in the API
 * and inherited an upstream tag typo: CacheRecord declares
 * `json:" Parents,omitempty"` with a LEADING SPACE, so the field went out as
 * " Parents" and the frontend's Parents was permanently undefined
 * (agent-os-iuby). Declaring our own type closes both problems for good — a
 * tag change upstream can no longer alter our contract.
 * The deprecated CacheRecord.Parent (singular, deprecated in API v1.42) is
 * deliberately not carried over; nothing consumed it.
 */
export interface BuildCacheEntry {
  id: string;
  parents?: string[];
  type: string;
  description: string;
  inUse: boolean;
  shared: boolean;
  size: number /* int64 */;
  createdAt: string;
  lastUsedAt: string | null;
  usageCount: number /* int */;
}
