// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/models. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: errors.go

/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrUnauthorized = "UNAUTHORIZED";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrForbidden = "FORBIDDEN";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrNotFound = "NOT_FOUND";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrValidation = "VALIDATION_ERROR";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrComposeValidation = "COMPOSE_VALIDATION_ERROR";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrDockerUnavailable = "DOCKER_UNAVAILABLE";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrDockerOperation = "DOCKER_OPERATION";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrGitDirty = "GIT_DIRTY";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrGitConflict = "GIT_CONFLICT";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrGitNotRepo = "GIT_NOT_REPO";
/**
 * ErrGitNoCommits is a repository that exists but has no commits yet — the
 * state `git init` leaves behind until the first commit. It is a ROUTINE
 * negative answer, not a client error, and it needs a code of its own
 * rather than ErrNotFound precisely because handlers/respond.go's
 * routineErrorCodes keys on the code: ErrNotFound is also the genuine
 * "Stack not found" error at 20 sites, so the two must not share (agent-os-n2df).
 */
export const ErrGitNoCommits = "GIT_NO_COMMITS";
/**
 * ErrStackDirMissing is a stack whose configured directory does not exist
 * on disk. It is NOT routine and is deliberately absent from
 * handlers/respond.go's routineErrorCodes: an unmounted stacks volume
 * produces it for every stack at once, and that must stay a warning.
 * It exists so that condition stops being answered as ErrGitNotRepo, which
 * sent an operator looking for a git problem when the volume was the fault.
 * The 404 is deliberate and unchanged from agent-os-pawv, whose contract
 * was that this answer be a 404 that SAYS WHY; only the code moves, and it
 * now says why more precisely than ErrGitNotRepo did (agent-os-n2df).
 */
export const ErrStackDirMissing = "STACK_DIR_MISSING";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrGitRemoteUnreachable = "GIT_REMOTE_UNREACHABLE";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrPathTraversal = "PATH_TRAVERSAL";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrDuplicateStack = "DUPLICATE_STACK";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrStackNotFound = "STACK_NOT_FOUND";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrSessionExpired = "SESSION_EXPIRED";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrSetupRequired = "SETUP_REQUIRED";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrSetupAlreadyDone = "SETUP_ALREADY_DONE";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrRateLimited = "RATE_LIMITED";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrEncryptionUnavailable = "ENCRYPTION_KEY_MISSING";
/**
 * The two 401 codes are not interchangeable, and the frontend response
 * interceptor (frontend/src/lib/api.ts) branches on the difference:
 *   - ErrSessionExpired means "this session cannot be used" — no token, an
 *     unusable token, a session row that is gone or past its expiry, or a
 *     session whose user row no longer exists. The frontend logs the user out
 *     and navigates to /login on this code. It is minted by
 *     middleware.AuthMiddleware and by the handlers that discover the
 *     session's user is gone (handlers/settings.go, handlers/auth.go).
 *     handlers/ws.go follows it too as of agent-os-2zq, though nothing
 *     consumes its handshake body today: a browser cannot read a failed
 *     handshake, and frontend/src/lib/ws.ts keys reconnect policy on the
 *     close codes (4401/4429) rather than on these JSON codes.
 *   - ErrUnauthorized means "the credential you just supplied is wrong", with
 *     the session itself untouched: a wrong login password, a wrong current
 *     password on change-password, a wrong password at the env-unlock prompt.
 *     The frontend shows the message and leaves the user where they are.
 * Reaching for ErrSessionExpired on a credential path recreates agent-os-318,
 * where mistyping your own password bounced you to /login mid-session.
 */
export const ErrOperationInProgress = "OPERATION_IN_PROGRESS";
/**
 * ErrBackupRepoUnreachable is a configured backup repository that could not
 * be read: it may exist and hold every snapshot the user has, but this
 * request could not see it. It is deliberately NOT ErrNotFound — the
 * snapshot listing used to answer this state with an empty 200, which reads
 * as "you have never taken a backup" and invites the user to initialise a
 * repository over one that is merely unreachable (agent-os-81vr).
 * It carries 503 rather than 500: the request is well-formed and the server
 * is healthy, a dependency is not, and 503 is what makes the failure
 * retryable to a client that reads status classes.
 */
export const ErrBackupRepoUnreachable = "BACKUP_REPO_UNREACHABLE";
/**
 * ErrBackupRepoUninitialized is a backup repository that does not exist
 * yet: the probe reached the configured location and found nothing there.
 * It is emphatically NOT ErrBackupRepoUnreachable — the recoveries are
 * opposites. Creating a repository is correct here and destructive-adjacent
 * there, which is the whole distinction agent-os-81vr introduced RepoState
 * to carry.
 * It carries 409 rather than 404 or 500. The snapshot listing used to
 * answer this state with 500 "Failed to list snapshots" (agent-os-rg8h),
 * because a comment claimed the state fell through to an empty list and it
 * did not: restic exits 10, which becomes an error. 409 is the house shape
 * for "the server is fine, this resource is in a state that refuses the
 * request", it is what the same handler file already answers for
 * BACKUP_UNAVAILABLE, and it is the one status class the frontend's
 * classifyError passes `message` through intact. It used to be the ONLY
 * status class that did — 404 replaced the message with a fixed string and
 * a 5xx discarded it — but agent-os-mc4i fixed both arms, so that is no
 * longer a reason to prefer any status over another. 409 remains the
 * correct status here entirely on its own merits: "the server is fine,
 * this resource is in a state that refuses the request", matching what
 * this handler file already answers for BACKUP_UNAVAILABLE.
 */
export const ErrBackupRepoUninitialized = "BACKUP_REPO_UNINITIALIZED";
export interface AppError {
  code: string;
  message: string;
  details?: unknown;
}

//////////
// source: models.go

export interface User {
  id: string;
  username: string;
  createdAt: string;
  updatedAt: string;
}
export interface Session {
  id: string;
  userId: string;
  expiresAt: string;
  createdAt: string;
}
export interface Directory {
  path: string;
  name: string;
  rootDir?: string;
  isGitRepo: boolean;
  gitRemote: string;
  gitBranch: string;
  gitAuthType: string;
  gitSshKeyPath?: string;
  gitHttpsUser?: string;
  hasHttpsToken: boolean;
  scannedAt: string;
}
export interface Stack {
  id: string;
  directory: string;
  composeFile: string;
  envFile: string;
  projectName: string;
  status: string;
  /**
   * StatusStale is set when the live Docker read failed and Status is the
   * last one stored rather than the current one (agent-os-xjzr). omitempty
   * on purpose: responses that never attempt a live read (Create) must not
   * send an explicit false, which would claim a liveness nobody checked.
   */
  statusStale?: boolean;
  containers: Container[];
  isGitRepo: boolean;
  gitBranch: string;
  gitCommit: string;
  gitDirty: boolean;
  gitAhead: number /* int */;
  gitBehind: number /* int */;
}
export interface Container {
  id: string;
  name: string;
  image: string;
  state: string;
  status: string;
  ports: PortBinding[];
  health: string;
}
export interface PortBinding {
  host: string;
  container: string;
  protocol: string;
}
export interface ContainerMetrics {
  containerId: string;
  name: string;
  cpuPercent: number /* float64 */;
  memUsage: number /* float64 */;
  memLimit: number /* float64 */;
  memPercent: number /* float64 */;
  netRx: number /* float64 */;
  netTx: number /* float64 */;
  blockRead: number /* float64 */;
  blockWrite: number /* float64 */;
  memSwap: number /* float64 */;
  pids: number /* uint64 */;
}
export interface GitCommit {
  hash: string;
  short: string;
  author: string;
  email: string;
  message: string;
  date: string;
}
export interface LintResult {
  level: string;
  line: number /* int */;
  message: string;
  rule: string;
}
export interface ActionLog {
  id: string;
  userId: string;
  stackId: string;
  action: string;
  detail: string;
  requestId?: string;
  createdAt: string;
}
export interface GitStatusResult {
  branch: string;
  commit: GitCommit;
  dirty: boolean;
  dirtyCount: number /* int */;
  ahead: number /* int */;
  behind: number /* int */;
  remoteUrl: string;
  trackingBranch: string;
  /**
   * IsBare marks a repository with no work tree (agent-os-m2g8). Dirty,
   * DirtyCount, Ahead, Behind and TrackingBranch are not measured for it and
   * stay zero; handlers/git.go leaves them out of the body.
   */
  isBare: boolean;
}
export interface PullResult {
  previousCommit: string;
  currentCommit: string;
  changedFiles: string[];
}
export interface LogResult {
  commits: GitCommit[];
  total: number /* int */;
  hasMore: boolean;
}
export interface DiffResult {
  /**
   * A value, not a pointer: getDiffCLI fills it on every success path, so
   * the wire always carries an object and the generated type says so
   * (agent-os-apmw).
   */
  commit: GitCommit;
  diff: string;
  files: string[];
}
export interface DashboardContainerInfo {
  id: string;
  name: string;
  image: string;
  state: string;
  status: string;
  health: string;
  ports: PortBinding[];
  stackId: string;
  /**
   * StackLookupFailed distinguishes the two causes of an empty StackID: the
   * compose project is genuinely not a stack, or the stacks table could not be
   * READ. Consumers that route on StackID must not conflate them -- see
   * resolveDashboardStackAssociation (services/docker.go) and agent-os-g482.
   */
  stackLookupFailed: boolean;
  projectName: string;
  restartCount: number /* int */;
  created: string;
  startedAt: string;
  diskSize: number /* int64 */;
  imageSize: number /* int64 */;
}
export interface DockerImage {
  id: string;
  repoTags: string[];
  size: number /* int64 */;
  created: number /* int64 */;
  containers: number /* int */;
}
export interface DockerVolume {
  name: string;
  driver: string;
  mountpoint: string;
  size: number /* int64 */;
  sizeKnown: boolean;
  inUse: boolean;
  created: string;
  stack: string;
}
export interface DockerNetwork {
  id: string;
  name: string;
  driver: string;
  scope: string;
  internal: boolean;
  containers: number /* int */;
  labels: string[];
  created: string;
  stack: string;
}
export interface ContainerUpdateInfo {
  containerId: string;
  containerName: string;
  image: string;
  imageRef: string;
  state: string;
  stackId: string;
  projectName: string;
  serviceName: string;
  isCompose: boolean;
  /**
   * LocalDigest is the repo-matched local digest resolved during detection,
   * carried through so performScan can persist it in cached_updates (finding #7).
   * It is set on the live-scan path (CheckForUpdates), so it appears in that
   * /updates response; the cached-read projections rebuild the struct without it.
   * omitempty only suppresses it where unset.
   */
  localDigest?: string;
  /**
   * RemoteDigest is the remote index digest resolved during detection (the same
   * value selectUpdates compared against LocalDigest to decide an update exists),
   * carried through so performScan can persist it without a re-fetch. Like
   * LocalDigest it is set on the live-scan path and appears in that /updates
   * response; the cached-read projections omit it.
   */
  remoteDigest?: string;
}
/**
 * StackEvent is the one envelope for every /ws/events frame. Status and
 * TargetType carry no omitempty: parseStackEvent requires status on
 * stack_status and update_job_* frames and targetType on update_job_* frames,
 * and every writer of those types sets them. Frame types that do not use them
 * send "" (agent-os-9kp2).
 */
export interface StackEvent {
  type: string;
  stackId?: string;
  containerId?: string;
  event?: string;
  status: string;
  timestamp: string;
  jobId?: string;
  targetType: string;
  targetId?: string;
  name?: string;
  error?: string;
  outcome?: string;
  reason?: string;
}
export interface CachedUpdate {
  id: string;
  containerId: string;
  containerName: string;
  image: string;
  imageRef: string;
  state: string;
  stackId?: string;
  projectName?: string;
  serviceName?: string;
  isCompose: boolean;
  localDigest: string;
  remoteDigest: string;
  scannedAt: string;
}
export interface AutoUpdatePolicy {
  id: string;
  targetType: string;
  targetId: string;
  enabled: boolean;
  consecutiveFailures: number /* int */;
  paused: boolean;
  createdAt: string;
  updatedAt: string;
}
export interface UpdateHistoryEntry {
  id: string;
  containerId: string;
  containerName: string;
  stackId?: string;
  stackName?: string;
  image: string;
  oldDigest?: string;
  newDigest?: string;
  oldImageRef?: string;
  newImageRef?: string;
  status: string;
  trigger: string;
  startedAt: string;
  completedAt?: string;
  durationMs?: number /* int64 */;
  errorMessage?: string;
}
export interface UpdateResult {
  oldDigest: string;
  newDigest: string;
  durationMs: number /* int64 */;
}
export interface UpdateSettingsResponse {
  scanIntervalMinutes: number /* int */;
  lastScanAt?: string;
  lastScanError?: string;
  globalAutoUpdate: boolean;
  /**
   * ApplyMode is "immediate" (apply on the scan tick) or "scheduled" (apply
   * at ApplyTime on ApplyDays).
   */
  applyMode: string;
  /**
   * ApplyTime is a wall-clock "HH:MM" in the server's local zone.
   */
  applyTime: string;
  /**
   * ApplyDays uses Go's weekday numbering, 0=Sunday..6=Saturday.
   * It must always marshal as a JSON array, never null: the frontend indexes
   * into it. A nil []int marshals to null, so every construction site
   * initialises it to []int{} before filling — and it deliberately carries no
   * omitempty, which would erase a legitimately empty selection back to
   * nothing at all.
   */
  applyDays: number /* int */[];
  /**
   * NextApplyAt is the next scheduled apply instant in RFC3339, omitted when
   * no apply is scheduled: immediate mode, auto-update off, or scanning
   * disabled (the apply timer lives inside the scan scheduler, so an interval
   * of 0 means nothing applies).
   */
  nextApplyAt?: string;
  /**
   * ServerTimezone and ServerTimeOffset are display-only, so the operator can
   * see which clock ApplyTime is interpreted against.
   */
  serverTimezone: string;
  serverTimeOffset: string;
  /**
   * AutoUpdateStats is ABSENT when the counts could not be read, never zeroed
   * (agent-os-xppj). A zeroed block renders as "0 containers with auto-update
   * enabled, 0 updates in the last 7 days, 0 in the last 30" — a wrong
   * factual answer where the convention agent-os-ufj7 restored promises an
   * absent one.
   * The rest of this response is still served when the counters fault: the
   * form above is the primary payload and refusing the whole request over an
   * ancillary block would delete a correct, populated write-back form from
   * the operator's screen. That split is this handler's existing policy, not
   * a new one — a failure of the settings read itself DOES 500.
   * KNOWN AND ACCEPTED: absence has two readings at the client — this server
   * could not count, or the server predates the field — and they are not
   * distinguished. Distinguishing them means a flag beside the numbers, which
   * leaves untrue zeros on the wire for any consumer that ignores it. The
   * frontend copy is chosen to be true under both readings.
   */
  autoUpdateStats?: UpdateStats;
}
/**
 * UpdateStats carries the auto-update counters. Named rather than inlined into
 * UpdateSettingsResponse so the response can omit the block wholesale when the
 * counts are unknown; an inline struct cannot be absent.
 */
export interface UpdateStats {
  enabledContainers: number /* int */;
  updatesLast7Days: number /* int */;
  updatesLast30Days: number /* int */;
}
export interface BackupPolicy {
  id: string;
  targetType: string;
  targetId: string;
  enabled: boolean;
  stopPolicy: string; // "stop" | "hot"
  createdAt: string;
  updatedAt: string;
}
export interface BackupRun {
  id: string;
  kind: string;
  trigger: string;
  status: string;
  startedAt: string;
  finishedAt?: string;
  stacksTotal: number /* int */;
  stacksOk: number /* int */;
  stacksFailed: number /* int */;
  bytesAdded?: number /* int64 */;
  errorMessage?: string;
}
export interface BackupRunItem {
  id: string;
  runId: string;
  stackId: string;
  status: string;
  snapshotId?: string;
  stopApplied: boolean;
  durationMs: number /* int64 */;
  errorMessage?: string;
}
export interface BackupSnapshot {
  id: string;
  shortId: string;
  time: string;
  hostname: string;
  tags: string[];
  paths: string[];
  sizeBytes?: number /* int64 */;
}
/**
 * DockerCleanupRun is one execution of the Docker image cleanup job.
 * MinAgeHours is stored per row rather than read from the live policy at
 * display time: a history entry has to stay interpretable after the policy
 * changes, and "why did this run remove so much" is unanswerable without the
 * age floor that run actually applied.
 */
export interface DockerCleanupRun {
  id: string;
  trigger: string; // "scheduled" | "manual"
  status: string; // "success" | "failed"
  startedAt: string;
  finishedAt?: string;
  imagesDeleted: number /* int */;
  bytesReclaimed: number /* int64 */;
  cacheBytesReclaimed: number /* int64 */;
  minAgeHours: number /* int */;
  errorMessage?: string;
}
