// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/services/wire_types.go. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: wire_types.go

/**
 * DiskUsageBreakdown is the per-category Docker disk usage served inside
 * GET /dashboard/stats's diskUsage field.
 */
export interface DiskUsageBreakdown {
  images: number /* int64 */;
  containers: number /* int64 */;
  volumes: number /* int64 */;
  buildCache: number /* int64 */;
  total: number /* int64 */;
}
/**
 * DockerCleanupCandidate is one image a run would remove. Repository is empty
 * for the fully-untagged form; see danglingRepository.
 */
export interface DockerCleanupCandidate {
  id: string;
  repository?: string;
  size: number /* int64 */;
  created: number /* int64 */;
}
/**
 * DockerCleanupPreview is what a run WOULD remove. Producing it must not remove
 * anything.
 * ReclaimableBytes is the dangling images only; CacheReclaimableBytes is the
 * build cache a run would also prune. They are separate because the history
 * row records them separately (bytesReclaimed, cacheBytesReclaimed), and the
 * operator-facing figure is their sum.
 */
export interface DockerCleanupPreview {
  candidates: DockerCleanupCandidate[];
  reclaimableBytes: number /* int64 */;
  cacheReclaimableBytes: number /* int64 */;
  minAgeHours: number /* int */;
}
/**
 * Status represents the lifecycle state of an update job.
 */
export const StatusQueued = "queued";
export const StatusPulling = "pulling";
export const StatusRecreating = "recreating";
export const StatusSuccess = "success";
export const StatusError = "error";
export type Status = typeof StatusQueued | typeof StatusPulling | typeof StatusRecreating | typeof StatusSuccess | typeof StatusError;
/**
 * Stream is one of the three allowed stream values for a LogLine.
 */
export const StreamStdout = "stdout";
export const StreamStderr = "stderr";
export const StreamStatus = "status";
export type Stream = typeof StreamStdout | typeof StreamStderr | typeof StreamStatus;
/**
 * JobTargetType is what an update job updates: one container or a whole stack.
 */
export const JobTargetTypeContainer = "container";
export const JobTargetTypeStack = "stack";
export type JobTargetType = typeof JobTargetTypeContainer | typeof JobTargetTypeStack;
/**
 * DoneStatus is the status a `done` frame on /ws/jobs carries: the terminal
 * subset of Status. Values are literals, not DoneStatus(StatusSuccess), because
 * tygo cannot evaluate a conversion and emits `unknown` for it; a test ties the
 * set to Status instead (agent-os-rc69).
 */
export const DoneStatusSuccess = "success";
export const DoneStatusError = "error";
export type DoneStatus = typeof DoneStatusSuccess | typeof DoneStatusError;
/**
 * StackStatus is a stack's status as the stacks API and the stack_status frame
 * on /ws/events report it. models.Stack.Status and models.StackEvent.Status
 * stay plain strings (models cannot import services); producers convert with
 * string(StackStatusX) (agent-os-rc69).
 */
export const StackStatusRunning = "running";
export const StackStatusStopped = "stopped";
export const StackStatusPartial = "partial";
export const StackStatusPaused = "paused";
export const StackStatusUnknown = "unknown";
export const StackStatusError = "error";
export type StackStatus = typeof StackStatusRunning | typeof StackStatusStopped | typeof StackStatusPartial | typeof StackStatusPaused | typeof StackStatusUnknown | typeof StackStatusError;
