// Code generated by tygo. DO NOT EDIT.
/**
 * Generated by tygo v0.2.21 from backend/internal/version. DO NOT EDIT.
 * Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate
 */

//////////
// source: version.go
/*
Package version carries the build identity stamped into the binary at link
time.

The values below are overridden by -ldflags "-X <import path>.Version=..." in
docker/Dockerfile's backend build stage. The defaults are deliberately
non-empty: an unstamped binary (a plain `go build`, or a local developer run)
reports "dev" rather than an empty string, which reads as a bug rather than as
"this was not built from a release tag".

A typo in an -X symbol path fails silently — the linker neither errors nor
warns, and the default survives. ldflags_test.go guards against that by
asserting the Dockerfile's -X paths match the symbols declared here.
*/

/**
 * Info is the build identity as served by GET /api/v1/version.
 */
export interface Info {
  version: string;
  commit: string;
  buildDate: string;
}
